import type { StremioManifest } from "../stremio/manifest";

export const FXGGXT_CATALOG_MAP: Record<string, { path: string; name: string }> = {
  "fxggxt-amateur": { path: "/tag/amateur-gay-porn/", name: "Amateur" },
  "fxggxt-bareback": { path: "/tag/bareback-gay-porn/", name: "Bareback" },
  "fxggxt-big-dick": { path: "/tag/big-dick-gay-porn/", name: "Big Dick" },
  "fxggxt-bisexual": { path: "/tag/bisexual-porn/", name: "Bisexual" },
  "fxggxt-group": { path: "/tag/group-gay-porn/", name: "Group" },
  "fxggxt-hunk": { path: "/tag/hunk-gay-porn-videos/", name: "Hunk" },
  "fxggxt-interracial": { path: "/tag/interracial-gay-porn/", name: "Interracial" },
  "fxggxt-muscle": { path: "/tag/muscle-gay-porn/", name: "Muscle" },
  "fxggxt-straight": { path: "/tag/straight-guys-gay-porn/", name: "Straight" },
  "fxggxt-twink": { path: "/tag/twink-gay-porn/", name: "Twink" },
  "fxggxt-4myfans": { path: "/category/4-myfans/", name: "4MyFans" },
  "fxggxt-activeduty": { path: "/category/active-duty/", name: "ActiveDuty" },
  "fxggxt-adulttime": { path: "/category/adulttime/", name: "AdultTime" },
  "fxggxt-allaustralianboys": { path: "/category/allaustralianboys/", name: "AllAustralianBoys" },
  "fxggxt-amateurgaypov": { path: "/category/amateurgaypov/", name: "AmateurGayPOV" },
  "fxggxt-amateursdoit": { path: "/category/amateursdoit/", name: "AmateursDoIt" },
  "fxggxt-american-muscle-hunks": { path: "/category/american-muscle-hunks/", name: "American Muscle Hunks" },
  "fxggxt-andolinixxl": { path: "/category/andolinixxl/", name: "AndoliniXXL" },
  "fxggxt-asgmax": { path: "/category/asgmax/", name: "ASGMax" },
  "fxggxt-badpuppy": { path: "/category/badpuppy/", name: "BadPuppy" },
  "fxggxt-baitbuddies": { path: "/category/baitbuddies/", name: "BaitBuddies" },
  "fxggxt-baitbus": { path: "/category/baitbus/", name: "BaitBus" },
  "fxggxt-barebackthathole": { path: "/category/barebackthathole/", name: "BarebackThatHole" },
  "fxggxt-beefcakehunter": { path: "/category/beefcake-hunter/", name: "BeefCakeHunter" },
  "fxggxt-bel-ami": { path: "/category/bel-ami/", name: "BelAmi" },
  "fxggxt-bentleyrace": { path: "/category/bentleyrace/", name: "BentleyRace" },
  "fxggxt-biguysfuck": { path: "/category/bi-guys-fuck/", name: "BiGuysFuck" },
  "fxggxt-bilatinmen": { path: "/category/bi-latin-men/", name: "BiLatinMen" },
  "fxggxt-blacksonboys": { path: "/category/blacksonboys/", name: "BlacksOnBoys" },
  "fxggxt-blakemason": { path: "/category/blakemason/", name: "BlakeMason" },
  "fxggxt-boys-halfway-house": { path: "/category/boys-halfway-house/", name: "Boys Halfway House" },
  "fxggxt-brandtsboys": { path: "/category/brandtsboys/", name: "BrandtsBoys" },
  "fxggxt-bravofucker": { path: "/category/bravofucker/", name: "BravoFucker" },
  "fxggxt-breederbros": { path: "/category/breederbros/", name: "BreederBros" },
  "fxggxt-breedmeraw": { path: "/category/breedmeraw/", name: "BreedMeRaw" },
  "fxggxt-bring-me-a-boy": { path: "/category/bring-me-a-boy/", name: "Bring Me A Boy" },
  "fxggxt-brokestraightboys": { path: "/category/brokestraightboys/", name: "BrokeStraightBoys" },
  "fxggxt-bromo": { path: "/category/bromo/", name: "Bromo" },
  "fxggxt-brothercrush": { path: "/category/say-uncle/brothercrush/", name: "BrotherCrush" },
  "fxggxt-brz-studios": { path: "/category/brz-studios/", name: "BRZ Studios" },
  "fxggxt-bullyhim": { path: "/category/say-uncle/bullyhim/", name: "BullyHim" },
  "fxggxt-chaosmen": { path: "/category/chaos-men/", name: "ChaosMen" },
  "fxggxt-citebeur": { path: "/category/citebeur/", name: "Citebeur" },
  "fxggxt-club-inferno-dungeon": { path: "/category/club-inferno-dungeon/", name: "Club Inferno Dungeon" },
  "fxggxt-clubamateurusa": { path: "/category/clubamateurusa/", name: "ClubAmateurUSA" },
  "fxggxt-clubbangboys": { path: "/category/clubbangboys/", name: "ClubBangBoys" },
  "fxggxt-cocksuremen": { path: "/category/cocksuremen/", name: "CockSureMen" },
  "fxggxt-cockyboys": { path: "/category/cocky-boys/", name: "CockyBoys" },
  "fxggxt-colbyknox": { path: "/category/colbyknox/", name: "ColbyKnox" },
  "fxggxt-collegeboyphysicals": { path: "/category/collegeboyphysicals/", name: "CollegeBoyPhysicals" },
  "fxggxt-collegedudes": { path: "/category/collegedudes/", name: "CollegeDudes" },
  "fxggxt-corbin-fisher": { path: "/category/corbin-fisher/", name: "CorbinFisher" },
  "fxggxt-creamybros": { path: "/category/creamybros/", name: "CreamyBros" },
  "fxggxt-crunchboy": { path: "/category/crunchboy/", name: "CrunchBoy" },
  "fxggxt-cumdumpsluts": { path: "/category/cumdumpsluts/", name: "CumDumpSluts" },
  "fxggxt-cutlersden": { path: "/category/cutlersden/", name: "CutlersDen" },
  "fxggxt-czech-hunter": { path: "/category/czech-hunter/", name: "Czech Hunter" },
  "fxggxt-dadcreep": { path: "/category/say-uncle/dadcreep/", name: "DadCreep" },
  "fxggxt-deviantotter": { path: "/category/deviantotter/", name: "DeviantOtter" },
  "fxggxt-devilsfilm": { path: "/category/devilsfilm/", name: "DevilsFilm" },
  "fxggxt-dickrides": { path: "/category/say-uncle/dickrides/", name: "DickRides" },
  "fxggxt-dirty-scout": { path: "/category/dirty-scout/", name: "Dirty Scout" },
  "fxggxt-disruptivefilms": { path: "/category/disruptivefilms/", name: "DisruptiveFilms" },
  "fxggxt-doctortapes": { path: "/category/say-uncle/doctortapes/", name: "DoctorTapes" },
  "fxggxt-dudesraw": { path: "/category/dudesraw/", name: "DudesRaw" },
  "fxggxt-eastboys": { path: "/category/eastboys/", name: "EastBoys" },
  "fxggxt-englishlads": { path: "/category/englishlads/", name: "EnglishLads" },
  "fxggxt-ericvideos": { path: "/category/ericvideos/", name: "EricVideos" },
  "fxggxt-euroboyxxx": { path: "/category/euroboyxxx/", name: "EuroBoyXXX" },
  "fxggxt-europeenz": { path: "/category/say-uncle/europeenz/", name: "EuroPeenz" },
  "fxggxt-extrabigdicks": { path: "/category/pride-studios/extrabigdicks/", name: "ExtraBigDicks" },
  "fxggxt-facedownassup": { path: "/category/facedownassup/", name: "FaceDownAssUp" },
  "fxggxt-falcon-studios": { path: "/category/falcon-studios/", name: "FalconStudios" },
  "fxggxt-familycreep": { path: "/category/pride-studios/familycreep/", name: "FamilyCreep" },
  "fxggxt-familycuckolds": { path: "/category/familycuckolds/", name: "FamilyCuckolds" },
  "fxggxt-familydick": { path: "/category/say-uncle/familydick/", name: "FamilyDick" },
  "fxggxt-fetishforce": { path: "/category/fetishforce/", name: "FetishForce" },
  "fxggxt-fitcasting": { path: "/category/fitcasting/", name: "FitCasting" },
  "fxggxt-fraternity-x": { path: "/category/fraternity-x/", name: "FraternityX" },
  "fxggxt-frenchdudes": { path: "/category/frenchdudes/", name: "FrenchDudes" },
  "fxggxt-frenchtwinks": { path: "/category/frenchtwinks/", name: "FrenchTwinks" },
  "fxggxt-freshmen": { path: "/category/freshmen/", name: "FreshMen" },
  "fxggxt-fuckermate": { path: "/category/fuckermate/", name: "FuckerMate" },
  "fxggxt-gaycest": { path: "/category/gaycest/", name: "GayCest" },
  "fxggxt-gay-hoopla": { path: "/category/gay-hoopla/", name: "GayHoopla" },
  "fxggxt-gayroom": { path: "/category/gayroom/", name: "GayRoom" },
  "fxggxt-grindhouseraw": { path: "/category/grindhouseraw/", name: "GrindHouseRaw" },
  "fxggxt-guybone": { path: "/category/guybone/", name: "GuyBone" },
  "fxggxt-guyselector": { path: "/category/guyselector/", name: "GuySelector" },
  "fxggxt-guysinsweatpants": { path: "/category/guysinsweatpants/", name: "GuysInSweatpants" },
  "fxggxt-helixstudios": { path: "/category/helixstudios/", name: "HelixStudios" },
  "fxggxt-himerostv": { path: "/category/himerostv/", name: "HimerosTV" },
  "fxggxt-hotboys-brazil": { path: "/category/hotboys-brazil/", name: "HotBoys Brazil" },
  "fxggxt-hotdadshotlads": { path: "/category/hotdadshotlads/", name: "HotDadsHotLads" },
  "fxggxt-hot-guys-fuck": { path: "/category/hot-guys-fuck/", name: "HotGuysFuck" },
  "fxggxt-hothouse": { path: "/category/hothouse/", name: "HotHouse" },
  "fxggxt-hotoldermale": { path: "/category/hotoldermale/", name: "HotOlderMale" },
  "fxggxt-hungfuckers": { path: "/category/hungfuckers/", name: "HungFuckers" },
  "fxggxt-hungpapi": { path: "/category/hungpapi/", name: "HungPapi" },
  "fxggxt-hungyoungbrit": { path: "/category/hungyoungbrit/", name: "HungYoungBrit" },
  "fxggxt-hunk-channel": { path: "/category/hunk-channel/", name: "Hunk Channel" },
  "fxggxt-iconmale": { path: "/category/iconmale/", name: "IconMale" },
  "fxggxt-iomacho": { path: "/category/iomacho/", name: "IOMacho" },
  "fxggxt-irmaosdotados": { path: "/category/irmaosdotados/", name: "IrmaosDotados" },
  "fxggxt-jalifstudio": { path: "/category/jalifstudio/", name: "JalifStudio" },
  "fxggxt-jasonsparkslive": { path: "/category/jasonsparkslive/", name: "JasonSparksLive" },
  "fxggxt-jawked": { path: "/category/jawked/", name: "Jawked" },
  "fxggxt-johnnyrapid": { path: "/category/johnnyrapid/", name: "JohnnyRapid" },
  "fxggxt-just-for-fans": { path: "/category/just-for-fans/", name: "JustForFans" },
  "fxggxt-kinkmen": { path: "/category/kinkmen/", name: "KinkMen" },
  "fxggxt-kristenbjorn": { path: "/category/kristenbjorn/", name: "KristenBjorn" },
  "fxggxt-latinboyz": { path: "/category/latinboyz/", name: "LatinBoyz" },
  "fxggxt-latinleche": { path: "/category/say-uncle/latinleche/", name: "LatinLeche" },
  "fxggxt-latinloads": { path: "/category/treasure-island-media/latinloads/", name: "LatinLoads" },
  "fxggxt-latinoguysporn": { path: "/category/say-uncle/latinoguysporn/", name: "LatinoGuysPorn" },
  "fxggxt-slowteasinghandjobs": { path: "/category/slowteasinghandjobs/", name: "SlowTeasingHandJobs" },
  "fxggxt-southernstrokes": { path: "/category/southernstrokes/", name: "SouthernStrokes" },
  "fxggxt-spritzz": { path: "/category/spritzz/", name: "Spritzz" },
  "fxggxt-spunkworthy": { path: "/category/spunkworthy/", name: "SpunkWorthy" },
  "fxggxt-stagcollective": { path: "/category/stagcollective/", name: "StagCollective" },
  "fxggxt-staghomme": { path: "/category/staghomme/", name: "StagHomme" },
  "fxggxt-stickyrub": { path: "/category/say-uncle/stickyrub/", name: "StickyRub" },
  "fxggxt-str8chaser": { path: "/category/str8chaser/", name: "Str8Chaser" },
  "fxggxt-str8hell": { path: "/category/str8hell/", name: "Str8Hell" },
  "fxggxt-tetatita": { path: "/category/tetatita/", name: "Tetatita" },
  "fxggxt-thebronetwork": { path: "/category/thebronetwork/", name: "TheBroNetwork" },
  "fxggxt-theguysite": { path: "/category/theguysite/", name: "TheGuySite" },
  "fxggxt-twinktrade": { path: "/category/say-uncle/twinktrade/", name: "TwinkTrade" },
  "fxggxt-uknakedmen": { path: "/category/uknakedmen/", name: "UKNakedMen" },
  "fxggxt-uncuttwinks": { path: "/category/uncuttwinks/", name: "UncutTwinks" },
  "fxggxt-varsitygrip": { path: "/category/say-uncle/varsitygrip/", name: "VarsityGrip" },
  "fxggxt-voyr": { path: "/category/voyr/", name: "VOYR" },
  "fxggxt-whynotbi": { path: "/category/whynotbi/", name: "WhyNotBi" },
  "fxggxt-william-higgins": { path: "/category/william-higgins/", name: "WilliamHiggins" },
  "fxggxt-xvideos-red": { path: "/category/xvideos-red/", name: "XVideosRed" },
  "fxggxt-yesfather": { path: "/category/say-uncle/yesfather/", name: "YesFather" },
  "fxggxt-youngbastards": { path: "/category/youngbastards/", name: "YoungBastards" },
  "fxggxt-youngperps": { path: "/category/youngperps/", name: "YoungPerps" },
};

export function buildFxggxtManifest(): StremioManifest {
  const catalogs: StremioManifest["catalogs"] = Object.entries(FXGGXT_CATALOG_MAP).map(([id, { name }]) => ({
    type: "movie",
    id,
    name,
    extra: [
      { name: "skip" },
    ],
  }));

  catalogs.unshift({
    type: "movie",
    id: "fxggxt-search",
    name: "Fxggxt Search",
    extra: [
      { name: "search", isRequired: true },
      { name: "skip" },
    ],
  });

  return {
    id: "community.fxggxt.stremio",
    version: "1.0.0",
    name: "Fxggxt",
    description: "Fxggxt content provider for Stremio - converted from Cloudstream 3 extension",
    resources: ["catalog", "meta", "stream"],
    types: ["movie"],
    catalogs,
    idPrefixes: ["fxggxt:"],
    behaviorHints: {
      adult: true,
      configurable: false,
    },
  };
}
