import type { StremioManifest } from "../stremio/manifest";

export const FXGGXT_CATALOG_MAP: Record<string, { path: string; name: string }> = {
  "fxggxt-amateur": { path: "/tag/amateur-gay-porn/", name: "FXXGT-Amateur" },
  "fxggxt-bareback": { path: "/tag/bareback-gay-porn/", name: "FXXGT-Bareback" },
  "fxggxt-big-dick": { path: "/tag/big-dick-gay-porn/", name: "FXXGT-Big Dick" },
  "fxggxt-bisexual": { path: "/tag/bisexual-porn/", name: "FXXGT-Bisexual" },
  "fxggxt-group": { path: "/tag/group-gay-porn/", name: "FXXGT-Group" },
  "fxggxt-hunk": { path: "/tag/hunk-gay-porn-videos/", name: "FXXGT-Hunk" },
  "fxggxt-interracial": { path: "/tag/interracial-gay-porn/", name: "FXXGT-Interracial" },
  "fxggxt-muscle": { path: "/tag/muscle-gay-porn/", name: "FXXGT-Muscle" },
  "fxggxt-straight": { path: "/tag/straight-guys-gay-porn/", name: "FXXGT-Straight" },
  "fxggxt-twink": { path: "/tag/twink-gay-porn/", name: "FXXGT-Twink" },
  "fxggxt-4myfans": { path: "/category/4-myfans/", name: "FXXGT-4MyFans" },
  "fxggxt-activeduty": { path: "/category/active-duty/", name: "FXXGT-ActiveDuty" },
  "fxggxt-adulttime": { path: "/category/adulttime/", name: "FXXGT-AdultTime" },
  "fxggxt-asgmax": { path: "/category/asgmax/", name: "FXXGT-ASGMax" },
  "fxggxt-badpuppy": { path: "/category/badpuppy/", name: "FXXGT-BadPuppy" },
  "fxggxt-baitbuddies": { path: "/category/baitbuddies/", name: "FXXGT-BaitBuddies" },
  "fxggxt-baitbus": { path: "/category/baitbus/", name: "FXXGT-BaitBus" },
  "fxggxt-barebackthathole": { path: "/category/barebackthathole/", name: "FXXGT-BarebackThatHole" },
  "fxggxt-bel-ami": { path: "/category/bel-ami/", name: "BelAmi" },
  "fxggxt-bentleyrace": { path: "/category/bentleyrace/", name: "FXXGT-BentleyRace" },
  "fxggxt-biguysfuck": { path: "/category/bi-guys-fuck/", name: "FXXGT-BiGuysFuck" },
  "fxggxt-bilatinmen": { path: "/category/bi-latin-men/", name: "FXXGT-BiLatinMen" },
  "fxggxt-blacksonboys": { path: "/category/blacksonboys/", name: "FXXGT-BlacksOnBoys" },
  "fxggxt-blakemason": { path: "/category/blakemason/", name: "FXXGT-BlakeMason" },
  "fxggxt-boys-halfway-house": { path: "/category/boys-halfway-house/", name: "FXXGT-Boys Halfway House" },
  "fxggxt-brandtsboys": { path: "/category/brandtsboys/", name: "FXXGT-BrandtsBoys" },
  "fxggxt-bravofucker": { path: "/category/bravofucker/", name: "FXXGT-BravoFucker" },
  "fxggxt-breederbros": { path: "/category/breederbros/", name: "FXXGT-BreederBros" },
  "fxggxt-breedmeraw": { path: "/category/breedmeraw/", name: "FXXGT-BreedMeRaw" },
  "fxggxt-bring-me-a-boy": { path: "/category/bring-me-a-boy/", name: "FXXGT-Bring Me A Boy" },
  "fxggxt-brokestraightboys": { path: "/category/brokestraightboys/", name: "FXXGT-BrokeStraightBoys" },
  "fxggxt-bromo": { path: "/category/bromo/", name: "FXXGT-Bromo" },
  "fxggxt-brothercrush": { path: "/category/say-uncle/brothercrush/", name: "FXXGT-BrotherCrush" },
  "fxggxt-brz-studios": { path: "/category/brz-studios/", name: "FXXGT-BRZ Studios" },
  "fxggxt-bullyhim": { path: "/category/say-uncle/bullyhim/", name: "FXXGT-BullyHim" },
  "fxggxt-chaosmen": { path: "/category/chaos-men/", name: "FXXGT-ChaosMen" },
  "fxggxt-citebeur": { path: "/category/citebeur/", name: "FXXGT-Citebeur" },
  "fxggxt-club-inferno-dungeon": { path: "/category/club-inferno-dungeon/", name: "FXXGT-Club Inferno Dungeon" },
  "fxggxt-clubamateurusa": { path: "/category/clubamateurusa/", name: "FXXGT-ClubAmateurUSA" },
  "fxggxt-clubbangboys": { path: "/category/clubbangboys/", name: "FXXGT-ClubBangBoys" },
  "fxggxt-cocksuremen": { path: "/category/cocksuremen/", name: "FXXGT-CockSureMen" },
  "fxggxt-cockyboys": { path: "/category/cocky-boys/", name: "FXXGT-CockyBoys" },
  "fxggxt-colbyknox": { path: "/category/colbyknox/", name: "FXXGT-ColbyKnox" },
  "fxggxt-collegeboyphysicals": { path: "/category/collegeboyphysicals/", name: "FXXGT-CollegeBoyPhysicals" },
  "fxggxt-collegedudes": { path: "/category/collegedudes/", name: "FXXGT-CollegeDudes" },
  "fxggxt-corbin-fisher": { path: "/category/corbin-fisher/", name: "FXXGT-CorbinFisher" },
  "fxggxt-creamybros": { path: "/category/creamybros/", name: "FXXGT-CreamyBros" },
  "fxggxt-crunchboy": { path: "/category/crunchboy/", name: "FXXGT-CrunchBoy" },
  "fxggxt-cumdumpsluts": { path: "/category/cumdumpsluts/", name: "FXXGT-CumDumpSluts" },
  "fxggxt-cutlersden": { path: "/category/cutlersden/", name: "FXXGT-CutlersDen" },
  "fxggxt-czech-hunter": { path: "/category/czech-hunter/", name: "FXXGT-Czech Hunter" },
  "fxggxt-dadcreep": { path: "/category/say-uncle/dadcreep/", name: "FXXGT-DadCreep" },
  "fxggxt-deviantotter": { path: "/category/deviantotter/", name: "FXXGT-DeviantOtter" },
  "fxggxt-devilsfilm": { path: "/category/devilsfilm/", name: "FXXGT-DevilsFilm" },
  "fxggxt-dickrides": { path: "/category/say-uncle/dickrides/", name: "FXXGT-DickRides" },
  "fxggxt-dirty-scout": { path: "/category/dirty-scout/", name: "FXXGT-Dirty Scout" },
  "fxggxt-disruptivefilms": { path: "/category/disruptivefilms/", name: "FXXGT-DisruptiveFilms" },
  "fxggxt-doctortapes": { path: "/category/say-uncle/doctortapes/", name: "FXXGT-DoctorTapes" },
  "fxggxt-dudesraw": { path: "/category/dudesraw/", name: "FXXGT-DudesRaw" },
  "fxggxt-eastboys": { path: "/category/eastboys/", name: "FXXGT-EastBoys" },
  "fxggxt-englishlads": { path: "/category/englishlads/", name: "FXXGT-EnglishLads" },
  "fxggxt-ericvideos": { path: "/category/ericvideos/", name: "FXXGT-EricVideos" },
  "fxggxt-euroboyxxx": { path: "/category/euroboyxxx/", name: "FXXGT-EuroBoyXXX" },
  "fxggxt-europeenz": { path: "/category/say-uncle/europeenz/", name: "FXXGT-EuroPeenz" },
  "fxggxt-extrabigdicks": { path: "/category/pride-studios/extrabigdicks/", name: "FXXGT-ExtraBigDicks" },
  "fxggxt-facedownassup": { path: "/category/facedownassup/", name: "FXXGT-FaceDownAssUp" },
  "fxggxt-falcon-studios": { path: "/category/falcon-studios/", name: "FXXGT-FalconStudios" },
  "fxggxt-familycreep": { path: "/category/pride-studios/familycreep/", name: "FXXGT-FamilyCreep" },
  "fxggxt-familycuckolds": { path: "/category/familycuckolds/", name: "FXXGT-FamilyCuckolds" },
  "fxggxt-familydick": { path: "/category/say-uncle/familydick/", name: "FXXGT-FamilyDick" },
  "fxggxt-fetishforce": { path: "/category/fetishforce/", name: "FXXGT-FetishForce" },
  "fxggxt-fitcasting": { path: "/category/fitcasting/", name: "FXXGT-FitCasting" },
  "fxggxt-fraternity-x": { path: "/category/fraternity-x/", name: "FXXGT-FraternityX" },
  "fxggxt-frenchdudes": { path: "/category/frenchdudes/", name: "FXXGT-FrenchDudes" },
  "fxggxt-frenchtwinks": { path: "/category/frenchtwinks/", name: "FXXGT-FrenchTwinks" },
  "fxggxt-freshmen": { path: "/category/freshmen/", name: "FXXGT-FreshMen" },
  "fxggxt-fuckermate": { path: "/category/fuckermate/", name: "FXXGT-FuckerMate" },
  "fxggxt-gaycest": { path: "/category/gaycest/", name: "FXXGT-GayCest" },
  "fxggxt-gay-hoopla": { path: "/category/gay-hoopla/", name: "FXXGT-GayHoopla" },
  "fxggxt-gayroom": { path: "/category/gayroom/", name: "FXXGT-GayRoom" },
  "fxggxt-grindhouseraw": { path: "/category/grindhouseraw/", name: "FXXGT-GrindHouseRaw" },
  "fxggxt-guybone": { path: "/category/guybone/", name: "FXXGT-GuyBone" },
  "fxggxt-guyselector": { path: "/category/guyselector/", name: "FXXGT-GuySelector" },
  "fxggxt-guysinsweatpants": { path: "/category/guysinsweatpants/", name: "FXXGT-GuysInSweatpants" },
  "fxggxt-helixstudios": { path: "/category/helixstudios/", name: "FXXGT-HelixStudios" },
  "fxggxt-himerostv": { path: "/category/himerostv/", name: "FXXGT-HimerosTV" },
  "fxggxt-hotboys-brazil": { path: "/category/hotboys-brazil/", name: "FXXGT-HotBoys Brazil" },
  "fxggxt-hotdadshotlads": { path: "/category/hotdadshotlads/", name: "FXXGT-HotDadsHotLads" },
  "fxggxt-hot-guys-fuck": { path: "/category/hot-guys-fuck/", name: "FXXGT-HotGuysFuck" },
  "fxggxt-hothouse": { path: "/category/hothouse/", name: "FXXGT-HotHouse" },
  "fxggxt-hotoldermale": { path: "/category/hotoldermale/", name: "FXXGT-HotOlderMale" },
  "fxggxt-hungfuckers": { path: "/category/hungfuckers/", name: "FXXGT-HungFuckers" },
  "fxggxt-hungpapi": { path: "/category/hungpapi/", name: "FXXGT-HungPapi" },
  "fxggxt-hungyoungbrit": { path: "/category/hungyoungbrit/", name: "FXXGT-HungYoungBrit" },
  "fxggxt-hunk-channel": { path: "/category/hunk-channel/", name: "FXXGT-Hunk Channel" },
  "fxggxt-iconmale": { path: "/category/iconmale/", name: "FXXGT-IconMale" },
  "fxggxt-iomacho": { path: "/category/iomacho/", name: "FXXGT-IOMacho" },
  "fxggxt-irmaosdotados": { path: "/category/irmaosdotados/", name: "FXXGT-IrmaosDotados" },
  "fxggxt-jalifstudio": { path: "/category/jalifstudio/", name: "FXXGT-JalifStudio" },
  "fxggxt-jasonsparkslive": { path: "/category/jasonsparkslive/", name: "FXXGT-JasonSparksLive" },
  "fxggxt-jawked": { path: "/category/jawked/", name: "FXXGT-Jawked" },
  "fxggxt-johnnyrapid": { path: "/category/johnnyrapid/", name: "FXXGT-JohnnyRapid" },
  "fxggxt-just-for-fans": { path: "/category/just-for-fans/", name: "FXXGT-JustForFans" },
  "fxggxt-kinkmen": { path: "/category/kinkmen/", name: "FXXGT-KinkMen" },
  "fxggxt-kristenbjorn": { path: "/category/kristenbjorn/", name: "FXXGT-KristenBjorn" },
  "fxggxt-latinboyz": { path: "/category/latinboyz/", name: "FXXGT-LatinBoyz" },
  "fxggxt-latinleche": { path: "/category/say-uncle/latinleche/", name: "FXXGT-LatinLeche" },
  "fxggxt-latinloads": { path: "/category/treasure-island-media/latinloads/", name: "FXXGT-LatinLoads" },
  "fxggxt-latinoguysporn": { path: "/category/say-uncle/latinoguysporn/", name: "FXXGT-LatinoGuysPorn" },
  "fxggxt-slowteasinghandjobs": { path: "/category/slowteasinghandjobs/", name: "FXXGT-SlowTeasingHandJobs" },
  "fxggxt-southernstrokes": { path: "/category/southernstrokes/", name: "FXXGT-SouthernStrokes" },
  "fxggxt-spritzz": { path: "/category/spritzz/", name: "FXXGT-Spritzz" },
  "fxggxt-spunkworthy": { path: "/category/spunkworthy/", name: "FXXGT-SpunkWorthy" },
  "fxggxt-stagcollective": { path: "/category/stagcollective/", name: "FXXGT-StagCollective" },
  "fxggxt-staghomme": { path: "/category/staghomme/", name: "FXXGT-StagHomme" },
  "fxggxt-stickyrub": { path: "/category/say-uncle/stickyrub/", name: "FXXGT-StickyRub" },
  "fxggxt-str8chaser": { path: "/category/str8chaser/", name: "FXXGT-Str8Chaser" },
  "fxggxt-str8hell": { path: "/category/str8hell/", name: "FXXGT-Str8Hell" },
  "fxggxt-tetatita": { path: "/category/tetatita/", name: "FXXGT-Tetatita" },
  "fxggxt-thebronetwork": { path: "/category/thebronetwork/", name: "FXXGT-TheBroNetwork" },
  "fxggxt-theguysite": { path: "/category/theguysite/", name: "FXXGT-TheGuySite" },
  "fxggxt-twinktrade": { path: "/category/say-uncle/twinktrade/", name: "FXXGT-TwinkTrade" },
  "fxggxt-uknakedmen": { path: "/category/uknakedmen/", name: "FXXGT-UKNakedMen" },
  "fxggxt-uncuttwinks": { path: "/category/uncuttwinks/", name: "FXXGT-UncutTwinks" },
  "fxggxt-varsitygrip": { path: "/category/say-uncle/varsitygrip/", name: "FXXGT-VarsityGrip" },
  "fxggxt-voyr": { path: "/category/voyr/", name: "FXXGT-VOYR" },
  "fxggxt-whynotbi": { path: "/category/whynotbi/", name: "FXXGT-WhyNotBi" },
  "fxggxt-william-higgins": { path: "/category/william-higgins/", name: "FXXGT-WilliamHiggins" },
  "fxggxt-xvideos-red": { path: "/category/xvideos-red/", name: "FXXGT-XVideosRed" },
  "fxggxt-yesfather": { path: "/category/say-uncle/yesfather/", name: "FXXGT-YesFather" },
  "fxggxt-youngbastards": { path: "/category/youngbastards/", name: "FXXGT-YoungBastards" },
  "fxggxt-youngperps": { path: "/category/youngperps/", name: "FXXGT-YoungPerps" }
};

export function buildFxggxtManifest(): StremioManifest {
  const catalogs: StremioManifest["catalogs"] = Object.entries(FXGGXT_CATALOG_MAP).map(([id, { name }]) => ({
    type: "movie",
    id,
    name,
    extra: [
      { name: "skip" },
    ],
  }));

  catalogs.unshift({
    type: "movie",
    id: "fxggxt-search",
    name: "Fxggxt Search",
    extra: [
      { name: "search", isRequired: true },
      { name: "skip" },
    ],
  });

  return {
    id: "community.fxggxt.stremio",
    version: "1.0.0",
    name: "Fxggxt",
    description: "Fxggxt content provider for Stremio - converted from Cloudstream 3 extension",
    resources: ["catalog", "meta", "stream"],
    types: ["movie"],
    catalogs,
    idPrefixes: ["fxggxt:"],
    behaviorHints: {
      adult: true,
      configurable: false,
    },
  };
}
